plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
remote_theme: pages-themes/cayman@v0.2.0
title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
